remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Computer Graphics Examples
description: Some example projects developed in blender, Unity, and other computer graphics software.